### PR TITLE
Bump obelisk to fix build on Mac OS

### PR DESCRIPTION
**Pull request by kmicklas**
Fixes https://github.com/reflex-frp/reflex-frp.org/issues/45.

### CODE REVIEW

**Comment by kmicklas** [comment]
@Ericson2314 I'm assuming this is no longer needed?

**Comment by Ericson2314** [comment]
Actually I think this probably still is needed (just newer develop). Need to add darwin to `release.nix` to tell.

**Comment by kmicklas** [comment]
@Ericson2314 bump.

**Comment by Ericson2314** [comment]
Bumped in the `v2` branch which should be merged to master since it's deployed

**Pull request closed without merging**
